// scripts/switch-schema.js
const fs = require('fs');
const path = require('path');
require('dotenv').config();

const DB_ENGINE = process.env.DB_ENGINE || 'mysql';
const prismaDir = path.join(__dirname, '..', 'prisma');
const targetSchema = path.join(prismaDir, 'schema.prisma');
const migrationLockFile = path.join(prismaDir, 'migrations', 'migration_lock.toml');

// Map DB_ENGINE to schema file and provider
const schemaMap = {
  'mysql': { schema: 'schema.mysql.prisma', provider: 'mysql' },
  'postgresql': { schema: 'schema.postgresql.prisma', provider: 'postgresql' },
  'postgres': { schema: 'schema.postgresql.prisma', provider: 'postgresql' }, // alias
};

const config = schemaMap[DB_ENGINE.toLowerCase()];

if (!config) {
  console.error(`❌ Unsupported DB_ENGINE: ${DB_ENGINE}`);
  console.error(`   Supported values: mysql, postgresql`);
  process.exit(1);
}

const sourceSchema = path.join(prismaDir, config.schema);

// Check if source schema exists
if (!fs.existsSync(sourceSchema)) {
  console.error(`❌ Schema file not found: ${sourceSchema}`);
  process.exit(1);
}

// Copy the appropriate schema file
try {
  fs.copyFileSync(sourceSchema, targetSchema);
  console.log(`✅ Switched to ${DB_ENGINE} schema`);
  console.log(`   Copied: ${config.schema} → schema.prisma`);
} catch (error) {
  console.error(`❌ Error copying schema file:`, error.message);
  process.exit(1);
}

// Update migration_lock.toml if it exists
if (fs.existsSync(migrationLockFile)) {
  try {
    const lockContent = `# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "${config.provider}"
`;
    fs.writeFileSync(migrationLockFile, lockContent);
    console.log(`✅ Updated migration lock file`);
    console.log(`   Provider: ${config.provider}`);
  } catch (error) {
    console.error(`⚠️  Warning: Could not update migration_lock.toml:`, error.message);
    // Don't exit - this is not critical for schema generation
  }
} else {
  console.log(`ℹ️  No migration_lock.toml found (will be created on first migration)`);
}
